### ISSUE TITLE
dynamodb already exists when adding autoscaling on existing stack.

### ISSUE THREAD

**Issue by TewodrosS** [medikoo/serverless-plugin-dynamodb-autoscaling#11]
An error occurred: ***TableWriteScalableTarget - table/****|dynamodb:table:WriteCapacityUnits|dynamodb already exists.

**Comment by medikoo** [comment]
hmm.. it shouldn't be the case, and normally isn't.

I take it might have happened on your side because you already have some autoscaling resources configured manually, or also use other auto-scaling plugin.

Please share some more info, a minimal reproducible test case, or content of `serverless.yml` will do

**Comment by TewodrosS** [comment]
In trying to create a repro step. I found out there was a manual configuration. removing that fixed it. Thanks!
